---

 - hosts: all
   become: true
   pre_tasks:

   - name: install updates (RedHat)
     tags: always
     yum:
       update_only: yes
       update_cache: yes
     when: ansible_distribution == "RedHat"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

   - name: add user simone
     tags: always
     user:
       name: simone
       groups: root

   - name: add ssh key for simone
     tags: always
     authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILvICaaCcJusFw93Gnu62H+/eALX89HpV9lqrrtjjWcV ansible"

   - name: add sudoers file for simone
     tags: always
     copy:
       src: sudoer_simone
       dest: /etc/sudoers.d/simone
       owner: root
       group: root
       mode: 0440

 - hosts:  workstations
   become: true
   tasks:

   - name: install unzip
     package:
       name: unzip

   - name: install terraform
     unarchive:
       src: https://releases.hashicorp.com/terraform/1.3.8/terraform_1.3.8_linux_arm64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root


 - hosts: web_servers
   become: true
   tasks:


   - name: install apache and php for Ubuntu servers
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: install apache and php for RedHat servers
     tags: apache,httpd,redhat
     yum:
       name:
         - httpd
         - php
       state: latest
     when: ansible_distribution == "RedHat"

   - name: change e-mail address or admin
     tags: apache, httpd, redhat
     lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin' 
        line: ServerAdmin somebody@something.com
     when: ansible_distribution == "RedHat"
     register: httpd

   - name: restart redhat
     tags: apache, httpd, redhat
     service:  
       name: httpd
       state: restarted
     when: httpd.changed

   - name: copy default html file for site
     tags: apache, apache2, httpd
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

   - name: start httpd (Ubuntu)
     tags: apache, ubuntu, httpd
     service:    
          name: apache2
          state: started
     when: ansible_distribution == "Ubuntu" 

 - hosts: db_servers
   become: true
   tasks:


   - name: start httpd (RedHat)
     tags: httpd, redhat,
     service:
          name: httpd
          state: started
          enabled: yes
     when: ansible_distribution == "RedHat"

   - name: change e-mail address or admin
     tags: apache, httpd, redhat
     lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@something.com
     when: ansible_distribution == "RedHat"
     register: httpd

   - name: restart redhat
     tags: apache, httpd, redhat
     service:
       name: httpd
       state: restarted
     when: httpd.changed
